---
framework   : deckjs        # {io2012, html5slides, revealjs, dzslides, ...}
deckjs:
  theme: swiss
  transition: horizontal-slide
  extensions: [goto, hash, menu, navigation, scale, status]
highlighter : highlight.js  # {highlight.js, prettify, highlight}
widgets     : [mathjax]# {mathjax, quiz, bootstrap}
hitheme     : solarized_light 
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides  
---



## Side effcts and safety of Metronidazole 
パネルディスカッション$-$「若年者除菌と胃がん予防」

#### Chaochen Wang$^1$, Yingsong Lin$^1$, Masumi Okuda$^2$, Shogo Kikuchi$^1$

1. Department Public Health, Aichi Medical University School of Medicine
2. Department of General Medicine and Community Health Science, Hyogo College of Medicine


---
## Background

> - **Metronidazole (MTZ)** has been broadly prescribed as therapy for $H. pylori$ eradication. 
> - Proton pump inhibitor(PPI) $+$ Amoxicillin(AMC) $+$ Clarithromycin $=$ **(PAC)** regimen had a significant lower **eradication rate** of $60.5\%$ compared with PPI $+$ AMC $+$ MTZ $=$ **PAM** regimen $(98.3\%)$ [unpublished data, Mabe _et al._] 
> - Resistance rate of clarithromycin in Japanese children is reported to be more than $40\%$.[Kato and Fujimura 2010]

--- 
## Carcinogenicity

> MTZ was categorized as **Possibly carcinogenic to human (2B)** 

> <cite>by International Agency for Research on Cancer, 1987</cite>




---

# Methods

--- 
## Pubmed searching 

###### (("Drug-Related Side Effects and Adverse Reactions"[Mesh]) AND "Metronidazole"[Mesh]) <br> OR <br> ( "Metronidazole/adverse effects"[Mesh] OR "Metronidazole/toxicity"[Mesh] ) <br> OR <br>  (("Metronidazole"[Mesh]) AND "Carcinogenicity Tests"[Mesh] )



---

# Results

---

# Discussion

--- 

# Conclusion




